### ISSUE TITLE
How to trigger mysqldump...

### ISSUE THREAD

**Issue by uschtwill** [kurthuwig/docker-duply#6]
...for mysql running in another container as part of pre routine/script? Or similar things necessary before backing up other containers?!

Hey there, thanks for this image!

Cheers
Will

**Comment by kurthuwig** [comment]
The problem is, that the whole point of having containers is to separate them. I can only think of two not so good ideas:

# run the mysqldump from the host before triggering the backup

# use cron to schedule a dump hopefully before the backup starts

I'd go for the first as I have to trigger the backup anyway.

**Comment by iBobik** [comment]
Theoretically it is possible to connect Duply container with Docker daemon socket:
```
volumes:
  - /var/run/docker.sock:/tmp/docker.sock
```
Then using curl you and REST API you can execute command inside container what have access to DB.

**Comment by uschtwill** [comment]
Yeah, I just ended up baking mysql-client package into our duply-backup image and running mysqldump from there as part of the pre script...
